import {
  Cable,
  Lightbulb,
  Settings,
  ShieldCheck,
  Snowflake,
  Zap,
} from "lucide-react";
import { BlogPost } from "../types/blog.types";

export const BLOG_POSTS: BlogPost[] = [
  {
    id: 1,
    title: "Mantenimiento especializado de subestaciones eléctricas",
    description: "IMESAC",
    image: "/mantenimiento_see.jpg",
    icon: Zap,
    category: "IMESAC",
    href: "/blog/mantenimiento-subestaciones-electricas",
    gridClass: "col-span-6 row-span-2",
  },
  {
    id: 2,
    title: "Sistemas HVAC de alta eficiencia energética",
    description: "Climatización",
    image: "/HVAC_2.jpg",
    icon: Snowflake,
    category: "Climatización",
    href: "/blog/sistemas-hvac-eficiencia-energetica",
    gridClass: "col-span-6 row-span-2",
  },
  {
    id: 3,
    title: "Certificación Defensa Civil",
    description: "Seguridad",
    image: "/HVAC_2.jpg",
    icon: ShieldCheck,
    category: "Seguridad",
    href: "/blog/certificacion-defensa-civil",
    gridClass: "col-span-3 row-span-1",
  },
  {
    id: 4,
    title: "Preventivo y correctivo",
    description: "Mantenimiento",
    image: "/mant_estructuras.jpg",
    icon: Settings,
    category: "Mantenimiento",
    href: "/blog/mantenimiento-preventivo-correctivo",
    gridClass: "col-span-3 row-span-1",
  },
  {
    id: 5,
    title: "Iluminación inteligente",
    description: "LED",
    image: "/iluminacion.jpg",
    icon: Lightbulb,
    category: "LED",
    href: "/blog/iluminacion-led-inteligente",
    gridClass: "col-span-3 row-span-1",
  },
  {
    id: 6,
    title: "Sistemas de puesta a tierra",
    description: "Seguridad",
    image: "/puesta_tierra.jpg",
    icon: Cable,
    category: "Seguridad",
    href: "/blog/sistemas-puesta-tierra",
    gridClass: "col-span-3 row-span-1",
  },
];
